//
// Created by Mahros on 12/31/2023.
//

#ifndef CSE014_PROJECT_01_GETPASS_H
#define CSE014_PROJECT_01_GETPASS_H
enum INPUT_ASCII {
    BACKSPACE = 8, // ASCII CODE FOR BACKSPACE
    ENTER = 13  // FOR ENTER BUTTON ASCII CODE
};

#endif //CSE014_PROJECT_01_GETPASS_H
